version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: biodiversity
      MYSQL_USER: phenus
      MYSQL_PASSWORD: ingavera
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: biodiversity
      DB_USER: phenus
      DB_PASSWORD: ingavera
    volumes:
      - .:/app
volumes:
  db-data:
